services:
        
  db:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 8806:3306

  server:
    container_name: php-apache
    build: ./server/
    ports:
      - 8000:80
    volumes:
      - "./server/php/src:/var/www/html/"
    depends_on:
      - db
      
